### ISSUE TITLE
Wrong Gradle Shadow Plugin version

### ISSUE THREAD

**Issue by djgarcias** [aol/micro-server#13]
Current version is causing the eclipse gradle plugin to fail see example below:

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\repositories\micro-server\build.gradle' line: 15

* What went wrong:
A problem occurred evaluating root project 'micro-server'.
> Failed to apply plugin [id 'com.github.johnrengelman.shadow']
   > No signature of method: com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar_Decorated.getManifest() is applicable for argument types: () values: []
Possible solutions: getManifest(), getManifest(), getManifest(), setManifest(org.gradle.api.java.archives.Manifest), setManifest(org.gradle.api.java.archives.Manifest), manifest(groovy.lang.Closure)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.122 secs

I fixed myself changing to the current version recommended on the wiki fo the project repository

https://github.com/johnrengelman/shadow to

classpath 'com.github.jengelman.gradle.plugins:shadow:1.2.0'

and worked well

**Comment by johnmcclean-aol** [comment]
Good job. Do you need permissions for a pull request?

**Comment by djgarcias** [comment]
Hi , yes , would be great

**Comment by johnmcclean-aol** [comment]
Hey - I think you should be able to fork it and submit a pull request back that way. Would you be able to give that a try?

Thanks a million!
