### ISSUE TITLE
roadmap of micro server

### ISSUE THREAD

**Issue by XuJun0909** [aol/micro-server#156]
can someone share the roadmap of micro server? will we add following features?:
1.circuit breaker
2.service bus
3.service monitor
4.service cluster and loadbalance

**Comment by johnmcclean-aol** [comment]
Hi Xu,

Over the next 12 months we will be focusing on adding features that make using Microserver in the cloud simpler. 

With specific regard to your requirements, a project that we are very excited about is [Spring Cloud](http://projects.spring.io/spring-cloud/). I think it offers all of the features you are looking for out of the box, and should be very simple to use with either the [micro-boot](https://github.com/aol/micro-server/tree/master/micro-boot) plugin (Microserver front end / Spring Boot backends) or the [micro-spring-boot](https://github.com/aol/micro-server/tree/master/micro-spring-boot) plugin (full-stack Spring boot managed server, with Microserver configuration also). Very often in the examples, using Spring Cloud is as simple as adding an annotation your your application. We will certainly be working to ensure Microserver has tight integration with Spring Boot and works with projects such as Spring Cloud.

If you don't like the auto-scanning functionality of Spring Boot, or would prefer alternatives to the Spring Cloud approach, it is pretty straightforward to create a Microserver plugin (see https://github.com/aol/micro-server/wiki/Creating-a-Microserver-plugin), and we will definitely be adding plugins ourselves where we feel we can simplify things over the next year. Community contributions for plugins (and ideas for plugins are very welcome!).

Outside of the Spring Cloud option, there is a [Javaslang CircuitBreaker](https://github.com/javaslang/javaslang-circuitbreaker) that we will add to the Javaslang plugin this year (an alternative to Spring Cloud's Hysterix plugin). 
We also have a custom smart load balancing client, based of micro-machine-stats and micro-application-register that we would love to open source (time permitting).

Another big focus will be on creating a detailed user manual, with worked examples. Explaining the range of options & extensions available when using Microserver.

I hope this helps clarify things, we will work to add a more detailed backlog of specific issues over the coming weeks.

Thanks,
John

**Comment by XuJun0909** [comment]
Hi John,
Thanks for your information. I reviewed some docs about spring cloud,it's a great framework that desiged to provide a bunch of useful libs for devs building distributed system. Curretly we use dubbox https://github.com/dangdangdotcom/dubbox in production to build our business, and I will also keep my eyes on the development of micro server , spring cloud etc.
Have a good day.

Thanks，
Doug

**Comment by johnmcclean-aol** [comment]
Thanks Doug!
