### ISSUE TITLE
Some Warnings from log file that need to be removed

### ISSUE THREAD

**Issue by morrowgi** [aol/micro-server#157]
During microserver startup I am seeing the following warns. They do not seem to impact startup but would be better if cleaned up:

Jan 26 2016 3:44:04 AM EST  WARN  org.springframework.context.annotation.ConfigurationClassEnhancer - @Bean method PropertyFileConfig.propertyPlaceholderConfigurer is non-static and returns an object assignable to Spring's BeanFactoryPostProcessor interface. This will result in a failure to process annotations such as @Autowired, @Resource and @PostConstruct within the method's declaring @Configuration class. Add the 'static' modifier to this method to avoid these container lifecycle issues; see @Bean javadoc for complete details.
 -- [main]

**Comment by johnmcclean-aol** [comment]
Released in 0.83
