### ISSUE TITLE
microserver-boot pom has incorrect dependency

### ISSUE THREAD

**Issue by gasbrakehonk** [aol/micro-server#16]
Having some issues with microservice boot dependencies. Looks like the generated pom for the microservices-boot is messed up. Namely it references 

   <dependency>
      <groupId>micro-server</groupId>
      <artifactId>micro-core</artifactId>
      <version>0.52</version>
      <scope>compile</scope>
    </dependency>

So when I attempt to use the shadow /  application plugin I get the following error.

FAILURE: Build failed with an exception.

* What went wrong:

Could not resolve all dependencies for configuration ':runtime'.

> Could not find micro-server:micro-core:0.52.

It should be 

<dependency>
   <groupId>com.aol.microservices</groupId>
      <artifactId>microserver-core</artifactId>
      <version>0.52</version>

etc...

**Comment by johnmcclean-aol** [comment]
This has been fixed with v0.53.1 of micro-boot.
