### ISSUE TITLE
Spring JDBC ROMA New Version

### ISSUE THREAD

**Issue by serkan-ozal** [aol/micro-server#177]
Hi, 
I had released new version of ROMA (https://github.com/serkan-ozal/spring-jdbc-roma-impl) with new features and performance improvements long time ago. As far as I see, this project uses its old version so I think, it would be better to use new version.

**Comment by johnmcclean-aol** [comment]
Hi Serkan,

We can create a micro-rowmapper plugin for this. It would be great if you could publish it to Maven Central or BinTray, it makes adding it as a dependency much simpler (esp. for end users as they need to also add the repo too) :)

Thanks,
John

**Comment by serkan-ozal** [comment]
Hi John,
Sure, I will publish it to Maven central.
Thanks for your response and interest.
If you have further request from ROMA which might be useful for you and users, please feel free to ping me :)

**Comment by johnmcclean-aol** [comment]
Captured in #180
