### ISSUE TITLE
com.aol.micro.server.auto.discovery.Rest doesn't work

### ISSUE THREAD

**Issue by mwnorman** [aol/micro-server#18]
ref my gist (https://gist.github.com/mwnorman/ed36b3c772d1973dcf1a)
I have created a simple test app ... my HelloResource is not being auto-magically discovered:

http://localhost:8080/simple/foo/hello 
  Resource identified by path '/simple/foo/hello', does not exist.

Am I missing something?

**Comment by johnmcclean-aol** [comment]
I'm guessing this is also dependency related. I'm upgrading to the latest Gradle. Gradle not including dependencies in the generate POM was an issue, but it's marked as resolved in their JIRA.

I can replicate the issue locally with your POM, will try and determine the exact cause.

**Comment by johnmcclean-aol** [comment]
This is a bug. As a temporary work around you can add the @Microserver annotation to TestMicroserverApp it will work.
Failing unit test added & fixed locally.

**Comment by johnmcclean-aol** [comment]
Tested locally, and working with v0.54 which is in Maven central now.

**Comment by kewangie** [comment]
Tested with v0.53. I believe that the HelloResource needs to be put a package where spring scans for for annotated components

**Comment by johnmcclean-aol** [comment]
Yep, the names of the packages Spring should scan weren't being configured correctly - when no Microserver annotation of Config object present. Fixed now in v0.54.
