### ISSUE TITLE
swagger-ui: basePath or apiPath?

### ISSUE THREAD

**Issue by mwnorman** [aol/micro-server#19]
I'm trying to get swagger-ui to work without much success - in
applications.properties do I need to specify swagger-ui's basePath or apiPath?

**Comment by johnmcclean-aol** [comment]
Hey Mike - 

Ke did most of the original swagger integration work, so I've assigned this to him.
You should get the swagger resource listing in your app by default at 

http://localhost:8080/simple/api-docs

(side note - we should ASAP upgrade from Swagger 1.2 to Swagger 2.0).

If you pass that in to swagger-ui (separate installation), it should be able to load and display the API details. (https://github.com/swagger-api/swagger-ui#swaggerui)

var swaggerUi = new SwaggerUi({
  url:"http://host:port/simple/api-docs",
  dom_id:"swagger-ui-container"
});

swaggerUi.load();

If you are doing this and swagger-ui can't read your resources, we may well have a bug.

**Comment by mwnorman** [comment]
I needed to handle CORS; however, the swagger-ui 'index.html' file in the 'dist' directory
of the Github checkout doesn't understand the context-root:

file:///D:/GitProjects/swagger-ui/dist/index.html#!/foo/hello
 try it --> http://localhost:8080/foo/hello
                                             ^^^
                should have '/simple' in there 

package com.windriver.simpleserver;

import java.io.IOException;

import javax.servlet.Filter;
import javax.servlet.FilterChain;
import javax.servlet.FilterConfig;
import javax.servlet.ServletException;
import javax.servlet.ServletRequest;
import javax.servlet.ServletResponse;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.springframework.stereotype.Component;

import com.aol.micro.server.auto.discovery.FilterConfiguration;

@Component
public class CORSFilterConfiguration implements FilterConfiguration {

	private static final String[] MAPPINGS = {"/simple/*"};
	
	@Override
	public String[] getMapping() {
		return MAPPINGS;
	}

	@Override
	public Class<? extends Filter> getFilter() {
		return CORSResponseFilter.class;
	}
	
	public static class CORSResponseFilter implements Filter {

		@Override
		public void init(FilterConfig filterConfig) throws ServletException {
		}

		@Override
		public void doFilter(ServletRequest request, ServletResponse response,
				FilterChain chain) throws IOException, ServletException {
			HttpServletResponse r = (HttpServletResponse) response;
		    String origin = ((HttpServletRequest) request).getHeader("origin");
		    r.addHeader("Access-Control-Allow-Origin", origin);
		    r.addHeader("Access-Control-Allow-Headers",
		            "Accept,Accept-Encoding,Accept-Language,Cache-Control,Connection,Content-Length,Content-Type," +
		            "Cookie,Host,Pragma,Referer,RemoteQueueID,User-Agent");
		    r.addHeader("Access-Control-Allow-Credentials", "true");
		    chain.doFilter(request, response);
		}

		@Override
		public void destroy() {
		}
		
	}
	
}

**Comment by kewangie** [comment]
Hi Mike, Just wondering if you have a com.aol.micro.server.module.ModuleBean defined?

**Comment by mwnorman** [comment]
No, its just a class with the @Component annotation - would a ModuleBean be better?

Also, any idea on how to use Swagger's API annotations to include the contextRoot?

**Comment by johnmcclean-aol** [comment]
Hi Ke,

By default, if none is provided we create one that defines the port, but not the host name. E.g.

     ModuleBean.builder().port(getPort(module)).build()

in Environment#assureModule

I think we can also extract the host automatically in most cases (but not all) via InetAddress.getLocalHost().getHostName()  (see http://stackoverflow.com/questions/7348711/recommended-way-to-get-hostname-in-java). And allow it to be overriden by a property (<app-name>.host) if needed.

Mike - This definetely needs cleaned up - but I think you can define a ModuleBean as a Spring bean and it will override the auto-created one (and you can set the actual host name directly on it). 

e.g.

    @Configuration
    public class AppConfig {
   
          @Value("${simple.app.host}")
          String hostname;

         @Bean
         public ModuleBean simpleAppModuleInfo(){
              ModuleBean.builder().port(port).host(hostname).build())
         }

   }

Sample from production code looks like this :-

        @Bean(name = "apiModuleBean")
	public ModuleBean configure() {
		return ModuleBean.builder().port(port).module(Modules.apiModule).host(host).build();
	}

**Comment by johnmcclean-aol** [comment]
Pull request submitted here : https://github.com/aol/micro-server/pull/20

**Comment by marcocast** [comment]
This has been fixed and it will be available on the next release.

Thanks all!
