### ISSUE TITLE
Variable substitution in properties is not being picked up by microserver

### ISSUE THREAD

**Issue by morrowgi** [aol/micro-server#24]
During installation of components using microserver. It is often nesecery to use command line variables to set log directories. In one such instance is the access logs. So currently micoroserver picks these up from the following property access.log.output.

If i initialize a variable in the start script for example like so:

export MY_APP=sample_microserver

If I add this property as follows:

access.log.output:/data/servers/${MY_APP}/logs/

The MY_APP variable does not get interpolated as sample_microserver.

Workaround is to hard code the access log location in the properties provided to the microservice

**Comment by kewangie** [comment]
Just clarify a few things here:

In the start script we do:
export MY_APP=sample_microserver

and then we do:
-DserverName=${MY_APP}

In the property file we do:
access.log.output=/data/servers/${serverName}/logs/

i.e. the system property serverName is not picked up by micro server

**Comment by kewangie** [comment]
should be fixed for the next release.

**Comment by johnmcclean-aol** [comment]
Released in 0.58
