### ISSUE TITLE
Micro server application registry generates too much logging

### ISSUE THREAD

**Issue by morrowgi** [aol/micro-server#256]
In the following class, the sendPing will log at info if it sucessfully can ping the registry. This should be moved to debug as when configuring the application to ping often it causes a lot of noise in the logs.

'    private void sendPing(RegisterEntry moduleEntry) {
        final RegisterEntry entry = moduleEntry.withTime(new Date())
                                               .withUuid(uuid)
                                               .withHealth(checker.isOk() ? Health.OK : Health.ERROR)
                                               .withStats(nonEmptyOrNull(statsChecker.stats()));
        try {

            logger.info("Posting {} to " + apiUrl + resourcePath, JacksonUtil.serializeToJson(entry));
            rest.post(apiUrl + resourcePath, JacksonUtil.serializeToJson(entry))
                .join();
        } catch (Exception e) {
            logger.warn("Failed posting {} to {}" + resourcePath, JacksonUtil.serializeToJson(entry), apiUrl);

        }
    }'

**Comment by johnmcclean-aol** [comment]
Released in 0.89.4 (https://github.com/aol/micro-server/pull/257)
