### ISSUE TITLE
Micro-event-datadog only works when explicitly definign the packages in @Microserver

### ISSUE THREAD

**Issue by morrowgi** [aol/micro-server#263]
I tried adding to my gradle file:

    compile "com.aol.microservices:micro-metrics-datadog:$microserverVersion"

however no metrics were being pushed to datadog.
I found the only way to get this working was to actually specify them in the main class as follows:
```

@Microserver(propertiesName = "my-app.properties",
             basePackages = { "com.aol.advertising.lana.myapp", "com.aol.micro.server.datadog.metrics",
                     "com.aol.micro.server.event.metrics" })
public class MyAppRestMain {

    public static void main(String[] args) {
        new MicroserverApp(
                           module("my-app/resource", MyAppRest.class)).start();
    }
```

**Comment by morrowgi** [comment]
Looks like the directory structure under resources is incorrect. I will create a PR to fix this

**Comment by johnmcclean-aol** [comment]
Impl https://github.com/aol/micro-server/pull/264
