### ISSUE TITLE
Micro-metrics-datadog only sends counts to datadog

### ISSUE THREAD

**Issue by morrowgi** [aol/micro-server#266]
In DatadogMetricsConfigurer we have the following:

        EnumSet<DatadogReporter.Expansion> expansions = EnumSet.of(COUNT);

This should be:

        EnumSet<DatadogReporter.Expansion> expansions = EnumSet.of(ALL);

This means only count metrics are being sent to datadog daemon

**Comment by johnmcclean-aol** [comment]
Fixed in https://github.com/aol/micro-server/issues/266
