### ISSUE TITLE
Trying to access Jersey ResourceConfig when using micro-server

### ISSUE THREAD

**Issue by cbelkas** [aol/micro-server#27]
Our team is using micro-server, and I'm trying to register an annotation for us to use with our authentication solution.

Is there a way to access the ResourceConfig (in com.aol.micro.server.rest.Jersey.JerseyRestApplication.java) when using the micro-server code?

**Comment by johnmcclean-aol** [comment]
Hi Chris,

Which method on the ResourceConfig do you need to call?

**Comment by cbelkas** [comment]
I need to use register() in order to access a custom binding in the auth
library we are using.

**Comment by johnmcclean-aol** [comment]
If it's a class you need to register you can add it to defaultResources in a ConfigurableModule. E.g.

      Module myModule =ConfigurableModule.context("my-app").defaultResources(ClassThatNeedsRegistered.class).build();
      new MicroserverApp(myModule);

If it's one of the other overloaded register methods, we may need to do something special to support it. One option would be to add a Consumer<ResourceConfig> to the Module, that can accept the ResourceConfig object and configure it how ever necessary. 

Let me know if the defaultResources option works for you and if not we can add the more flexible / powerful alternative.

**Comment by cbelkas** [comment]
After looking at an example sent to me and working with Ed today, I was
able to get the configuration to a place where I think it should be. I
still have a few other small things to do, but I should be in a good place
now. I'll update if not.

Thanks,
Chris

**Comment by cbelkas** [comment]
This specific issue is resolved - I was using an old version of micro-server.
