### ISSUE TITLE
Enhancement: DatadogMetricsConfigurer expansions should be configurable

### ISSUE THREAD

**Issue by morrowgi** [aol/micro-server#270]
In DatadogMetricsConfigurer the following means all metrics are pushed to datadog daemon:

`EnumSet<DatadogReporter.Expansion> expansions = EnumSet.of(ALL);`

This should be configurable via spring or otherwise

**Comment by johnmcclean-aol** [comment]
Duplicate of this one -> https://github.com/aol/micro-server/issues/258

**Comment by johnmcclean-aol** [comment]
Merged
