### ISSUE TITLE
RestAnnotationClasses not available in ConfigurableModule

### ISSUE THREAD

**Issue by cbelkas** [aol/micro-server#28]
Per the docs for the most recent micro-server, a way to add annotation classes should be available in ConfigurableModule:

> default List<Class> getRestAnnotationClasses() {
>     return Arrays.asList(Rest.class);
> }

However, as of micro-server-0.5.8, there doesn't appear to be any way to add annotation classes via ConfigurableModule:

https://github.com/aol/micro-server/blob/master/micro-core/src/main/java/com/aol/micro/server/module/ConfigurableModule.java

**Comment by johnmcclean-aol** [comment]
Hey Chris,

The Pull Request is here. https://github.com/aol/micro-server/pull/29

**Comment by cbelkas** [comment]
Cool thanks - I'll keep an eye on it. Is there anything I need to do except wait for the merge/new dependency?

**Comment by cbelkas** [comment]
Hi - as of today the changes made in 0.59 does not seem to address the issues I am having.

Usually when using Jersey's ResourceConfig I would call register() and either pass in the class or an instantiated object. For our uses, the object it creates is populated by a filter we are using. However, when using the annotation, the object always comes through null when using it.

Could someone let me know if there is an issue with the new change in ConfigurableModule, or if our uses are outside the scope of what restAnnotationClasses is supposed to handle? Maybe I've misunderstood the purpose of this configuration option?

**Comment by johnmcclean-aol** [comment]
See also : https://github.com/aol/micro-server/issues/32

**Comment by johnmcclean-aol** [comment]
This is being tracked by this issue : https://github.com/aol/micro-server/issues/32

**Comment by johnmcclean-aol** [comment]
Internal OAuth annotations work in 0.84 (to be released soon). Finally :)
