### ISSUE TITLE
HashMapBuilder lost build() method in version 0.62

### ISSUE THREAD

**Issue by marcocast** [aol/micro-server#53]
the following piece of code that was working in version 0.59, is now not working as the build() disappear in the new version breaking existing code.
HashMapBuilder.of("wadl", wadl).build().

**Comment by johnmcclean-aol** [comment]
Hey Marco,

Slight change to this API (simplified) and brought more in line with the
Java 8 convention for 'of' methods. of actually creates the map so this
will work

         Map m = HashMapBuilder.of("wadl", wadl);

To get the same functionality as before

          Map m = HashMapBuilder.map("wadl", wadl).build();

On Wed, Aug 12, 2015 at 8:31 AM, Marco Castigliego <notifications@github.com

**Comment by marcocast** [comment]
Cool, thanks John.
