### ISSUE TITLE
Can't make it work in a Groovy script

### ISSUE THREAD

**Issue by jeancarlozapata** [aol/micro-server#56]
Hi!

This looks like a very nice project. By its simplicity I started trying to write a Groovy script but couldn't make it work due to the lambda used on the ```init``` method.

I tried something like this:

```groovy
@Grab('com.aol.microservices:micro-core:0.62')

import com.aol.micro.server.*
import com.aol.micro.server.auto.discovery.*
import javax.ws.rs.*

@Rest
@Path("/status")
class StatusApp {

    static void main(String[] args){
        def init = { -> "status-app"}
        def app = new MicroserverApp(init)
        // also tried like this
        //def app = new MicroserverApp({ -> "status-app" })
        app.run()
    }

    @GET
    @Produces("text/plain")
	@Path("/ping")
    String respondToPing() {
        return "pong!"
    }
}
```
I know this is probably related to how Groovy handles Java 8 lambdas (I've been Googling but can not find a way to use a Groovy closure as a Java lambda for this case). What would be the best approach to make this script work?

Any help or pointers in the right direction would be very appreciated.

Thanks

**Comment by johnmcclean-aol** [comment]
@jeancarlozapata  Thanks! You can use the Groovy *as* keyword to coerce the Groovy closure to a Java 8 Functional Interface (see http://www.infoq.com/articles/groovy-to-Java-8).

e.g. 

       Function f =  { a ->a+1 } as Function

I haven't run this code, but have made use of this technique in the past.
```groovy
@Rest
@Path("/status")
class StatusApp {

    static void main(String[] args){
        Module init = { -> "status-app"} as Module
        def app = new MicroserverApp(init)
        // also tried like this
        //def app = new MicroserverApp({ -> "status-app" })
        app.run()
    }

    @GET
    @Produces("text/plain")
    @Path("/ping")
    String respondToPing() {
        return "pong!"
    }
}
```

**Comment by jeancarlozapata** [comment]
Hi @johnmcclean-aol, thanks for your response. Been busy this week. Will try to test it over the weekend (or just will move the example to Java :wink:). Anyway, I will post the results and/or solution here.

**Comment by johnmcclean-aol** [comment]
We need to supply the current class to MicroserverApp to determine the base class  for Spring package scanning (if none is supplied MicroserverApp tries to figure this out from the StackTrace - which is probably different for Groovy). So this get's things a bit futher 
```groovy
@Rest
@Path("/status")
@Microserver
class StatusGroovy {

	static void main(String[] args){
		
		def app = new MicroserverApp(StatusGroovy,{ -> "status-app"} as Module).start()
		
	}

	@GET
	@Produces("text/plain")
	@Path("/ping")
	public String respondToPing() {
		return "pong!"
	}
}
```

**Comment by johnmcclean-aol** [comment]
In fact that works for me now.
