### ISSUE TITLE
Spring seems does not like bean classes with the same name

### ISSUE THREAD

**Issue by kewangie** [aol/micro-server#61]
Fox example:

In micro-mysql and micro-data plugins, we have:
com.aol.micro.server.mysql.distlock.datasource.DataSourceBuilder
com.aol.micro.server.spring.datasource.DataSourceBuilder

when both plugins appear on classpath, applications always can not find "mainDataSource" bean which should instantiated by com.aol.micro.server.spring.datasource.DataSourceBuilder

**Comment by johnmcclean-aol** [comment]
fixed in Microserver 0.68
