### ISSUE TITLE
SpringDataConfig issue in data plugin

### ISSUE THREAD

**Issue by kewangie** [aol/micro-server#63]
vendorAdapter.setGenerateDdl(true);

seems cause application to hang

should that be:
vendorAdapter.setGenerateDdl(false);

**Comment by johnmcclean-aol** [comment]
Is is this in one of the tests ? (Which one :)

**Comment by kewangie** [comment]
No, it is not a test. I actually deployed ingester jar to the server and SpringDataConfig seems try to create db sachems. The application hangs after this log:
org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean - Building JPA container EntityManagerFactory for persistence unit 'default'

**Comment by johnmcclean-aol** [comment]
You are right, this is a bug for sure.

**Comment by johnmcclean-aol** [comment]
Fixed by Ke on master
