### ISSUE TITLE
CORs module needs enhanced

### ISSUE THREAD

**Issue by johnmcclean-aol** [aol/micro-server#72]
Current CORs filter, is pretty basic (wrt features & configurability). A more advanced one should be pluggable also (perhaps the ebay CORs Filter).

**Comment by edeegan** [comment]
I see that Spring 4.2 has a configurable annotation for CORS:

https://spring.io/blog/2015/06/08/cors-support-in-spring-framework

**Comment by johnmcclean-aol** [comment]
Looks like it is for Spring MVC - there may be a Jersey equivalent though.

**Comment by johnmcclean-aol** [comment]
released in 0.76
