### ISSUE TITLE
SQL class does not have update or queryForObject methods

### ISSUE THREAD

**Issue by marcocast** [aol/micro-server#8]
MyRestEndPoint class in the micro-tutorial fails compilation due to missing methods in the DAO interface. It works perfectly if I comment out the create and get services in MyRestEndPoint

**Comment by colmg** [comment]
On 18/03/2015 11:43, Marco Castigliego wrote:
>
> MyRestEndPoint class in the micro-tutorial fails compilation due to 
> missing methods in the DAO interface. It works perfectly if I comment 
> out the create and get services in MyRestEndPoint
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/aol/micro-server/issues/8>.
>
Yes, I found that issue also.

This is fixed in the following pull request :

https://github.com/aol/micro-server/pull/7

**Comment by johnmcclean-aol** [comment]
Fix merged to master
